version: "3"
services:
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app_network

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
     - app_network

  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - './db_volumes:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_INITDB_ARGS: CREATE DATABASE db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge